### PR TITLE
Testing adding to this repo

### PR DESCRIPTION
**Pull request by Christian-Fisher**
I am trying this to see if I can get code into cyberbattle... If this is bad, deny me

### CODE REVIEW

**Review by James-LG — CHANGES_REQUESTED** [review]
Can't you just add this exact code to MARLon? Where are you planning on using it that requires being in this repo?

Remember you'll have to push a new Docker container and we'll all have to pull it back down for every change here.

**Comment by Christian-Fisher** [comment]
I cloned cyberbattle into marlon, but it doesnt like importing it because it doesnt count as a "module". If there is a better way of doing this, I would do it

**Comment by James-LG** [comment]
I mean putting this in a MARLon file, don't touch CyberBattle at all. The simulations are started on the MARLon side anyways so they can set the defender to this new class, it doesn't actually have to be in CyberBattle. Think of MARLon as an extension to CyberBattle that depends on CyberBattle.

**Comment by Christian-Fisher** [comment]
Ohh I think I see, we basically need to make extensions of cyberbattle files that import the file we are attempting to edit. Ill try that out. Thanks

**Pull request closed without merging**
